# Generated by Django 2.2.5 on 2019-12-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeInfoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='addr',
            field=models.CharField(default='Bangalore', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='CEO', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='empid',
            field=models.CharField(default='e01', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='8899006622', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default='20000'),
            preserve_default=False,
        ),
    ]
